language: php
services: mysql
php:
  - "5.4"
env:
  - DB=mysql
before_script:
  - mysql -e 'CREATE DATABASE core_test;'
  - sudo hostname test.travis-ci.org
  - pecl install dbase
  - composer install

script:
- phpunit